### ISSUE TITLE
Install - getting requirements to build wheel did not run succesfully - deprecation in requirements?

### ISSUE THREAD

**Issue by alycialeonard** [carderne/ccg-spider#17]
Hi Chris, running into a new error trying to `pip install -e .` to set up spider prep on my Mac. Output below: 

```
(spider) alycialeonard@engs-27786 prep % pip install -e .
Obtaining file:///Users/alycialeonard/PycharmProjects/ccg-spider/prep
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting scipy>=1.8.0 (from spider==1.0.0)
  Downloading scipy-1.12.0-cp312-cp312-macosx_10_9_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 1.3 MB/s eta 0:00:00
Collecting rasterio>=1.0.7 (from spider==1.0.0)
  Downloading rasterio-1.3.9-cp312-cp312-macosx_10_15_x86_64.whl.metadata (14 kB)
Collecting rasterstats>=0.13.0 (from spider==1.0.0)
  Downloading rasterstats-0.19.0-py3-none-any.whl.metadata (4.1 kB)
Collecting geopandas>=0.10.2 (from spider==1.0.0)
  Downloading geopandas-0.14.3-py3-none-any.whl.metadata (1.5 kB)
Collecting typer>=0.0.12 (from spider==1.0.0)
  Downloading typer-0.9.0-py3-none-any.whl.metadata (14 kB)
Collecting PyYAML>=5.1 (from spider==1.0.0)
  Downloading PyYAML-6.0.1-cp312-cp312-macosx_10_9_x86_64.whl.metadata (2.1 kB)
Collecting h3pandas>=0.2.3 (from spider==1.0.0)
  Downloading h3pandas-0.2.6.tar.gz (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.4/138.4 kB 2.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pygeos>=0.12.0 (from spider==1.0.0)
  Downloading pygeos-0.14.tar.gz (141 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.3/141.3 kB 2.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      <string>:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      /private/var/folders/z3/0jh63h9s12zgjdfyzynfh20r0000gr/T/pip-install-3nreegm_/pygeos_ca34b17f6a384b5ebb7ccda9be1f9cd9/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Could not find geos-config executable. Either append the path to geos-config to PATH or manually provide the include_dirs, library_dirs, libraries and other link args for compiling against a GEOS version >=3.5.
      Compiling pygeos/_geometry.pyx because it changed.
      Compiling pygeos/_geos.pyx because it changed.
      [1/2] Cythonizing pygeos/_geometry.pyx
      [2/2] Cythonizing pygeos/_geos.pyx
      Traceback (most recent call last):
        File "/Users/alycialeonard/miniforge3/envs/spider/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/alycialeonard/miniforge3/envs/spider/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/alycialeonard/miniforge3/envs/spider/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/z3/0jh63h9s12zgjdfyzynfh20r0000gr/T/pip-build-env-070ndjpt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/z3/0jh63h9s12zgjdfyzynfh20r0000gr/T/pip-build-env-070ndjpt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/z3/0jh63h9s12zgjdfyzynfh20r0000gr/T/pip-build-env-070ndjpt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 214, in <module>
        File "/private/var/folders/z3/0jh63h9s12zgjdfyzynfh20r0000gr/T/pip-install-3nreegm_/pygeos_ca34b17f6a384b5ebb7ccda9be1f9cd9/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/z3/0jh63h9s12zgjdfyzynfh20r0000gr/T/pip-install-3nreegm_/pygeos_ca34b17f6a384b5ebb7ccda9be1f9cd9/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/z3/0jh63h9s12zgjdfyzynfh20r0000gr/T/pip-install-3nreegm_/pygeos_ca34b17f6a384b5ebb7ccda9be1f9cd9/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by alycialeonard** [comment]
FYI I was able to get it running by making my own environment with the dependencies and then running the `pip install -e .` command so seems likely to be something in the dependency setup.

**Comment by carderne** [comment]
I'm unable to install `pygeos` under Python 3.12 at all.
https://github.com/pygeos/pygeos/issues/463

Are you on Python 3.12?

**Comment by alycialeonard** [comment]
Nope! I'm on 3.11.6 in this environment. Here's the full package list: 
```
(spider) alycialeonard@engs-27786 GeoH2-data-prep % mamba list      
# packages in environment at /Users/alycialeonard/miniforge3/envs/spider:
#
# Name                    Version                   Build  Channel
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.7.4                hbe6ead2_2    conda-forge
aws-c-cal                 0.6.2                hfc10710_2    conda-forge
aws-c-common              0.9.3                h0dc2134_0    conda-forge
aws-c-compression         0.2.17               hd41bdd4_3    conda-forge
aws-c-event-stream        0.3.2                he52df9d_2    conda-forge
aws-c-http                0.7.13               hb43ddd7_2    conda-forge
aws-c-io                  0.13.33              h2566903_0    conda-forge
aws-c-mqtt                0.9.7                h6b10715_0    conda-forge
aws-c-s3                  0.3.17               h5800b94_4    conda-forge
aws-c-sdkutils            0.1.12               hd41bdd4_2    conda-forge
aws-checksums             0.1.17               hd41bdd4_2    conda-forge
aws-crt-cpp               0.24.2               hf47b73b_2    conda-forge
aws-sdk-cpp               1.10.57             h98cd3c2_24    conda-forge
blosc                     1.21.5               heccf04b_0    conda-forge
boost-cpp                 1.78.0               hf5ba120_3    conda-forge
branca                    0.7.1              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                h0dc2134_1    conda-forge
brotli-bin                1.1.0                h0dc2134_1    conda-forge
brotli-python             1.1.0           py311hdf8f085_1    conda-forge
bzip2                     1.0.8                h10d778d_5    conda-forge
c-ares                    1.27.0               h10d778d_0    conda-forge
ca-certificates           2024.2.2             h8857fd0_0    conda-forge
cairo                     1.16.0            h09dd18c_1016    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cfitsio                   4.2.0                hd56cc12_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0           py311h7bea37d_0    conda-forge
curl                      8.4.0                h726d00d_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hf0c8a7f_1    conda-forge
fiona                     1.9.4           py311h4c3e48b_0    conda-forge
folium                    0.16.0             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               h5bb23bf_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.49.0          py311he705e18_0    conda-forge
freetype                  2.12.1               h60636b9_2    conda-forge
freexl                    1.0.6                hb7f2c08_1    conda-forge
gdal                      3.7.0           py311hfbd0d3d_3    conda-forge
geopandas                 0.14.3             pyhd8ed1ab_0    conda-forge
geopandas-base            0.14.3             pyha770c72_0    conda-forge
geos                      3.11.2               hf0c8a7f_0    conda-forge
geotiff                   1.7.1               h5cf5d3c_11    conda-forge
gettext                   0.21.1               h8a4c099_0    conda-forge
giflib                    5.2.1                hb7f2c08_3    conda-forge
h3-py                     3.7.6           py311hdf8f085_1    conda-forge
h3pandas                  0.2.6              pyhd8ed1ab_0    conda-forge
hdf4                      4.2.15               h9804679_6    conda-forge
hdf5                      1.14.1          nompi_hedada53_100    conda-forge
icu                       72.1                 h7336db1_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.0.1              pyha770c72_0    conda-forge
jinja2                    3.1.3              pyhd8ed1ab_0    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
json-c                    0.16                 h01d06f9_0    conda-forge
kealib                    1.5.1                h7014c1b_4    conda-forge
kiwisolver                1.4.5           py311h5fe6e05_1    conda-forge
krb5                      1.21.2               hb884880_0    conda-forge
lcms2                     2.15                 h2dcdeff_1    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libaec                    1.1.2                he965462_1    conda-forge
libarchive                3.6.2                h0b5dc4a_1    conda-forge
libblas                   3.9.0           21_osx64_openblas    conda-forge
libbrotlicommon           1.1.0                h0dc2134_1    conda-forge
libbrotlidec              1.1.0                h0dc2134_1    conda-forge
libbrotlienc              1.1.0                h0dc2134_1    conda-forge
libcblas                  3.9.0           21_osx64_openblas    conda-forge
libcurl                   8.4.0                h726d00d_0    conda-forge
libcxx                    16.0.6               hd57cbcb_0    conda-forge
libdeflate                1.18                 hac1461d_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 h10d778d_2    conda-forge
libexpat                  2.5.0                hf0c8a7f_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgdal                   3.7.0                h1aad74f_3    conda-forge
libgfortran               5.0.0           13_2_0_h97931a8_3    conda-forge
libgfortran5              13.2.0               h2873a65_3    conda-forge
libglib                   2.78.1               h6d9ecee_0    conda-forge
libiconv                  1.17                 hd75f5a5_2    conda-forge
libjpeg-turbo             2.1.5.1              h0dc2134_1    conda-forge
libkml                    1.3.0             hab3ca0e_1016    conda-forge
liblapack                 3.9.0           21_osx64_openblas    conda-forge
libnetcdf                 4.9.2           nompi_hb79a6a3_109    conda-forge
libnghttp2                1.58.0               h64cf6d3_0    conda-forge
libopenblas               0.3.26          openmp_hfef2a42_0    conda-forge
libpng                    1.6.43               h92b6c6a_0    conda-forge
libpq                     15.4                 h3df487d_2    conda-forge
librttopo                 1.1.0               h5c328d2_13    conda-forge
libspatialindex           1.9.3                he49afe7_4    conda-forge
libspatialite             5.0.1               h54d511b_27    conda-forge
libsqlite                 3.45.1               h92b6c6a_0    conda-forge
libssh2                   1.11.0               hd019ec5_0    conda-forge
libtiff                   4.5.1                hf955e92_1    conda-forge
libwebp-base              1.3.2                h0dc2134_0    conda-forge
libxcb                    1.15                 hb7f2c08_0    conda-forge
libxml2                   2.11.5               hd95e348_0    conda-forge
libzip                    1.10.1               hc158999_3    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
llvm-openmp               17.0.6               hb6ac08f_0    conda-forge
lz4-c                     1.9.4                hf0c8a7f_0    conda-forge
lzo                       2.10              haf1e3a3_1000    conda-forge
mapclassify               2.6.1              pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5           py311he705e18_0    conda-forge
matplotlib-base           3.8.3           py311h6ff1f5f_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
munch                     4.0.0              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  h93d8f39_2    conda-forge
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
nspr                      4.35                 hea0b92c_0    conda-forge
nss                       3.98                 ha05da47_0    conda-forge
numpy                     1.26.4          py311hc43a94b_0    conda-forge
openjpeg                  2.5.0                h13ac156_2    conda-forge
openssl                   3.1.5                hd75f5a5_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.2.1           py311h8f6166a_0    conda-forge
pcre2                     10.40                h1c4e4bc_0    conda-forge
pillow                    10.0.0          py311h7cb0e2d_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.43.4               h73e2aa4_0    conda-forge
poppler                   23.05.0              he041c3a_1    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                15.4                 hc940a54_2    conda-forge
proj                      9.2.1                hc8d59c9_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
pygeos                    0.14            py311heb7bb94_1    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyproj                    3.6.1           py311h854a015_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.6          h30d4d87_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py311h2725bcf_1    conda-forge
rasterio                  1.3.7           py311h5f90dc6_2    conda-forge
rasterstats               0.19.0             pyhd8ed1ab_0    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rich                      13.7.1             pyhd8ed1ab_0    conda-forge
rtree                     1.2.0           py311hbc1f44b_0    conda-forge
scikit-learn              1.4.1.post1     py311he2b4599_0    conda-forge
scipy                     1.12.0          py311h86d0cd9_2    conda-forge
setuptools                69.1.1             pyhd8ed1ab_0    conda-forge
shapely                   2.0.1           py311heb7bb94_1    conda-forge
shellingham               1.5.4              pyhd8ed1ab_0    conda-forge
simplejson                3.19.2          py311he705e18_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h225ccf5_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
spider                    1.0.0                    pypi_0    pypi
sqlite                    3.45.1               h7461747_0    conda-forge
threadpoolctl             3.3.0              pyhc1e730c_0    conda-forge
tiledb                    2.13.2               h8b9cbf0_0    conda-forge
tk                        8.6.13               h1abcd95_1    conda-forge
typer                     0.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.10.0               hd8ed1ab_0    conda-forge
typing_extensions         4.10.0             pyha770c72_0    conda-forge
tzcode                    2024a                h10d778d_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
uriparser                 0.9.7                he965462_1    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.4                h90c7484_2    conda-forge
xorg-libxau               1.0.11               h0dc2134_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xyzservices               2023.10.1          pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h8a1eda9_5    conda-forge
zstd                      1.5.5                h829000d_0    conda-forge
```

**Comment by carderne** [comment]
Just pushed some changes.

Pull them to local and you should be able to install.
